{
 "title": "Beacon Node status",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "source",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"ethereum-monitor\",\r\n  tag: \"source\",\r\n  predicate: (r) => r._measurement == \"beacon_node_info\",\r\n  start: -30d\r\n)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"ethereum-monitor\",\r\n  tag: \"network\",\r\n  predicate: (r) => r._measurement == \"beacon_block_info\",\r\n  start: -30d\r\n)"
    }
   },
   {
    "name": "interval",
    "query": "10s,30s,1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Execution Layer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ethereum-monitor\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"beacon_node_info\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"el_offline\")\r\n  |> filter(fn: (r) => r[\"endpoint\"] == \"/eth/v1/node/syncing\")\r\n  |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: if r._value == true then 1 else 0\r\n  }))"
    }
   ]
  },
  {
   "title": "Health status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ethereum-monitor\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"beacon_node_info\")\r\n  |> filter(fn: (r) => r[\"endpoint\"] == \"/eth/v1/node/health\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"status_code\")\r\n  |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Is optimistic",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ethereum-monitor\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"beacon_node_info\")\r\n  |> filter(fn: (r) => r._field == \"is_optimistic\")\r\n  |> filter(fn: (r) => r[\"endpoint\"] == \"/eth/v1/node/syncing\")\r\n  |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: if r._value == true then 1 else 0\r\n  }))"
    }
   ]
  },
  {
   "title": "Sincronizado",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ethereum-monitor\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"beacon_node_info\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"is_syncing\")\r\n  |> filter(fn: (r) => r[\"endpoint\"] == \"/eth/v1/node/syncing\")\r\n  |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: if r._value == true then 1 else 0\r\n  }))"
    }
   ]
  },
  {
   "title": "Estado del nodo a lo largo del tiempo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Head Slot",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"ethereum-monitor\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"beacon_node_info\")\r\n  |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> filter(fn: (r) => r[\"endpoint\"] == \"/eth/v1/node/syncing\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"head_slot\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Cantidad de peers conectados",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"ethereum-monitor\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"beacon_node_info\")\r\n  |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> filter(fn: (r) => r[\"endpoint\"] == \"/eth/v1/node/peer_count\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"connected\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Cantidad de peers conectandose",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"ethereum-monitor\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"beacon_node_info\")\r\n  |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> filter(fn: (r) => r[\"endpoint\"] == \"/eth/v1/node/peer_count\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"connecting\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Distancia de sincronización",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"ethereum-monitor\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"beacon_node_info\")\r\n  |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> filter(fn: (r) => r[\"endpoint\"] == \"/eth/v1/node/syncing\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sync_distance\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Cantidad de peers desconectados",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"ethereum-monitor\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"beacon_node_info\")\r\n  |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> filter(fn: (r) => r[\"endpoint\"] == \"/eth/v1/node/peer_count\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disconnecting\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Cantidad de peers desconenctadose",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"ethereum-monitor\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"beacon_node_info\")\r\n  |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> filter(fn: (r) => r[\"endpoint\"] == \"/eth/v1/node/peer_count\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disconnected\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}