{
 "title": "Beacon config",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "source",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"ethereum-monitor\",\r\n  tag: \"source\",\r\n  predicate: (r) => r._measurement == \"beacon_config_info\",\r\n  start: -30d\r\n)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"ethereum-monitor\",\r\n  tag: \"network\",\r\n  predicate: (r) => r._measurement == \"beacon_config_info\",\r\n  start: -30d\r\n)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Parametros de la red",
   "type": "table",
   "description": "Parametros de la configuracion actual de la red de ethereum",
   "gridPos": { "h": 29, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ethereum-monitor\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"beacon_config_info\")\r\n  |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> filter(fn: (r) => r[\"endpoint\"] == \"/eth/v1/config/spec\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n      nombre: r._field,\r\n      valor: string(v: r._value)  // convierte todo a string\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "Current Fork Epoch ",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ethereum-monitor\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"beacon_config_info\")\r\n  |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> filter(fn: (r) => r[\"endpoint\"] == \"/eth/v1/beacon/states/head/fork\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"epoch\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "All Fork Epoch",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 16, "x": 8, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"ethereum-monitor\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"beacon_config_info\")\r\n  |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> filter(fn: (r) => r[\"endpoint\"] == \"/eth/v1/config/fork_schedule\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"epoch\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}