{
 "title": "Block metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "source",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"ethereum-monitor\",\r\n  tag: \"source\",\r\n  predicate: (r) => r._measurement == \"beacon_block_info\",\r\n  start: -30d\r\n)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"ethereum-monitor\",\r\n  tag: \"network\",\r\n  predicate: (r) => r._measurement == \"beacon_block_info\",\r\n  start: -30d\r\n)"
    }
   },
   {
    "name": "interval",
    "query": "12s,384s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "block_id", "query": "head,finalized" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Slot",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"ethereum-monitor\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"beacon_block_info\")\r\n  |> filter(fn: (r) => r[\"endpoint\"] == \"/eth/v2/beacon/blocks/${block_id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"message.slot\")\r\n  |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Block number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"ethereum-monitor\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"beacon_block_info\")\r\n  |> filter(fn: (r) => r[\"endpoint\"] == \"/eth/v2/beacon/blocks/${block_id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"message.body.execution_payload.block_number\")\r\n  |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Gas metrics ETH",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"ethereum-monitor\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"beacon_block_info\")\r\n  |> filter(fn: (r) => r[\"endpoint\"] == \"/eth/v2/beacon/blocks/${block_id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"message.body.execution_payload.base_fee_per_gas\" or r[\"_field\"] == \"message.body.execution_payload.blob_gas_used\" or r[\"_field\"] == \"message.body.execution_payload.excess_blob_gas\" or r[\"_field\"] == \"message.body.execution_payload.gas_limit\" or r[\"_field\"] == \"message.body.execution_payload.gas_used\")\r\n  |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 1000000000.0 }))\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Sum of amounts ETH",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"ethereum-monitor\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"beacon_block_info\")\r\n  |> filter(fn: (r) => r[\"endpoint\"] == \"/eth/v2/beacon/blocks/${block_id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sum_withdrawals_amount\" or r[\"_field\"] == \"sum_exec_req_withdrawal_amount\" or r[\"_field\"] == \"sum_exec_req_deposit_amount\" or r[\"_field\"] == \"sum_deposit_amount\")\r\n  |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 1000000000.0 }))\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Contadores",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"ethereum-monitor\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"beacon_block_info\")\r\n  |> filter(fn: (r) => r[\"endpoint\"] == \"/eth/v2/beacon/blocks/${block_id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count_attestations\" or r[\"_field\"] == \"count_attester_slashings\" or r[\"_field\"] == \"count_blob_kzg_commitments\" or r[\"_field\"] == \"count_bls_to_execution_changes\" or r[\"_field\"] == \"count_deposits\" or r[\"_field\"] == \"count_exec_req_consolidations\" or r[\"_field\"] == \"count_exec_req_deposits\" or r[\"_field\"] == \"count_exec_req_withdrawals\" or r[\"_field\"] == \"count_proposer_slashings\" or r[\"_field\"] == \"count_voluntary_exits\" or r[\"_field\"] == \"count_withdrawals\" or r[\"_field\"] == \"count_transactions\")\r\n  |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  { "title": "Checkpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Epoch values and status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "query": "from(bucket: \"ethereum-monitor\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"beacon_block_info\")\r\n  |> filter(fn: (r) => r[\"endpoint\"] == \"/eth/v1/beacon/states/${block_id}/finality_checkpoints\")\r\n  |> filter(fn: (r) => r[\"_field\"] != \"timestamp_df\")\r\n  |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  { "title": "Rewards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Rewards values ETH",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "query": "from(bucket: \"ethereum-monitor\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"beacon_block_info\")\r\n  |> filter(fn: (r) => r[\"endpoint\"] == \"/eth/v1/beacon/rewards/blocks/${block_id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] != \"timestamp_df\" and r[\"_field\"] != \"proposer_index\")\r\n  |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 1000000000.0 }))\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  { "title": "Blobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Cantidad de blobs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "query": "from(bucket: \"ethereum-monitor\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"beacon_block_info\")\r\n  |> filter(fn: (r) => r[\"endpoint\"] == \"/eth/v1/beacon/blob_sidecars/${block_id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}